name: Npm Publish
on:
  push:
    branches:
      - main
    paths:
      - packages/**/package.json

jobs:
  npm-publish:
    name: npm publish
    strategy:
      matrix:  
        version: [10, 12, 14, 16, 18]
        os: [ubuntu-latest, windows-latest]
        include:
          - package: './dist/packages/gimit'
          - package: './dist/packages/git'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: npm install

      - name: Build dependencies
        run: npm run build
      
      - name: Publish Package
        run: npm publish ${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
